export const siteConfig = {
  name: "Programador Web Full Stack",
  default: "Martin Ferreira | Programador Web Full Stack",
  author: "Martín Ferreira Yic",
  description:
    "Soy Martin Ferreira Yic, un Programador Web Full Stack. En mi portafolio, proyectos que reflejan mi pasión por crear soluciones web. Te invito a explorar mi trabajo y descubrir cómo combino mis habilidades técnicas y creativas para ofrecer experiencias digitales de calidad superior.",
  keywords: [
    "martin",
    "martín",
    "ferreira",
    "yic",
    "martin ferreira yic",
    "martín ferreira yic",
    "programador",
    "web",
    "full stack",
    "mern",
    "next.js",
    "css",
    "html",
    "typescript",
    "node",
    "astro",
    "desarrollador web",
    "express",
    "tailwind",
    "react",
    "javascript",
    "reactjs",
    "nodejs",
    "nextjs",
  ],
  links: {
    linkedin: "https://www.linkedin.com/in/martin-ferreira-yic/",
    github: "https://github.com/martinfyic",
  },
  url: "https://www.martin-ferreira.com",
  mail: "martin.f.yic@gmail.com",
  verification: {
    google: "-DJdilV6UgRDNbs6BKKyIYeO62gitX7Hqd9oYyu-vNA",
  },
};
